### ISSUE TITLE
how to avoid duplicate names in tree updates?  currently easy to crash in docs tree examples.

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#1007]
### Describe the bug

need to make tree copy / paste / drag-n-drop more robust to duplicate names, which can be easily created in many cases.  don't want the app to crash in this case: need to rename the child.  need to decide at what level to do this etc.

### How to reproduce

in docs app, in Collections/Trees, drag first `node-base-0` onto `node-base-1` and do `Add To Children`..

### Relevant output

```shell
Crash log saved in /Users/oreilly/Library/Cogent\ Core\ Docs/crash-logs

Platform: MacOS
System platform: MacOS
App version: v0.2.0-408-ge38cea5a2
Core version: v0.2.0-408-ge38cea5a2
Time: 2024-07-13 00:13:59

panic: plan.Update: duplicate name: tv_node-base-0

goroutine 51 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/runtime/debug/stack.go:24 +0x64
cogentcore.org/core/core.handleRecover({0x106ab5560, 0x14014c57c60})
	/Users/oreilly/go/src/cogentcore.org/core/core/recover.go:38 +0x74
cogentcore.org/core/core.(*renderWindow).eventLoop.func1()
	/Users/oreilly/go/src/cogentcore.org/core/core/renderwindow.go:393 +0x34
panic({0x106ab5560?, 0x14014c57c60?})
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/runtime/panic.go:770 +0x124
cogentcore.org/core/base/plan.Update[...](0x14012179538, 0x2, 0x140112995b8, 0x14011299598, 0x14011299580, 0x106d61ed0)
	/Users/oreilly/go/src/cogentcore.org/core/base/plan/update.go:50 +0x864
cogentcore.org/core/tree.UpdateSlice(0x2?, {0x106d83cd8?, 0x14012179508?}, {0x14014c6bbc0?, 0x14015229b80?, 0xb?})
	/Users/oreilly/go/src/cogentcore.org/core/tree/typeplan.go:34 +0xac
cogentcore.org/core/tree.Update({0x106d83cd8, 0x14012179508}, {0x14014c6bbc0, 0x2, 0x2})
	/Users/oreilly/go/src/cogentcore.org/core/tree/typeplan.go:56 +0x58
cogentcore.org/core/core.(*Tree).syncToSrc(0x14012179508, 0x14011299810, 0x0, 0x1)
	/Users/oreilly/go/src/cogentcore.org/core/core/treesync.go:80 +0x250
cogentcore.org/core/core.(*Tree).setSyncNode(...)
	/Users/oreilly/go/src/cogentcore.org/core/core/treesync.go:47
cogentcore.org/core/core.(*Tree).syncToSrc(0x140119d0a88, 0x14011299810, 0x0, 0x0)
	/Users/oreilly/go/src/cogentcore.org/core/core/treesync.go:87 +0x294
cogentcore.org/core/core.(*Tree).Resync(0x140119d0a88)
	/Users/oreilly/go/src/cogentcore.org/core/core/treesync.go:54 +0x34
cogentcore.org/core/core.(*Tree).sendChangeEventReSync(0x14012179508, {0x140112998b8?, 0x14013facb00?, 0x10513989c?})
	/Users/oreilly/go/src/cogentcore.org/core/core/tree.go:836 +0x54
cogentcore.org/core/core.(*Tree).pasteChildrenSync(0x14012179508, {0x14013d9b5a0?, 0x0?, 0x0?}, 0x0?)
	/Users/oreilly/go/src/cogentcore.org/core/core/treesync.go:472 +0xac
cogentcore.org/core/core.(*Tree).pasteChildren(0xfffffffffffffdec?, {0x14013d9b5a0?, 0x14011299968?, 0x1051398b4?}, 0x0?)
	/Users/oreilly/go/src/cogentcore.org/core/core/tree.go:1468 +0x34
cogentcore.org/core/core.(*Tree).MakePasteMenu.func2({0x106b65420?, 0x14014b71260?})
	/Users/oreilly/go/src/cogentcore.org/core/core/tree.go:1352 +0x38
cogentcore.org/core/events.(*Listeners).Call(0x14011299a18, {0x106d95568, 0x14014b77ea0}, {0x14011299a00, 0x1, 0x2?})
	/Users/oreilly/go/src/cogentcore.org/core/events/listeners.go:61 +0x104
cogentcore.org/core/core.(*WidgetBase).HandleEvent.func1(0x14014b71260)
	/Users/oreilly/go/src/cogentcore.org/core/core/widgetevents.go:244 +0x5c
cogentcore.org/core/base/tiered.(*Tiered[...]).Do(0x0, 0x14011299a98?)
	/Users/oreilly/go/src/cogentcore.org/core/base/tiered/tiered.go:30 +0x48
cogentcore.org/core/core.(*WidgetBase).HandleEvent(0x140136a0408, {0x106d95568?, 0x14014b77ea0?})
	/Users/oreilly/go/src/cogentcore.org/core/core/widgetevents.go:243 +0x124
cogentcore.org/core/core.(*WidgetBase).Send(0x140136a0408, 0x5, {0x14011299d40?, 0x107c645b8?, 0x10?})
	/Users/oreilly/go/src/cogentcore.org/core/core/widgetevents.go:180 +0x80
cogentcore.org/core/core.(*Events).handlePosEvent(0x14012210108, {0x106d957e8, 0x14015155dc0})
	/Users/oreilly/go/src/cogentcore.org/core/core/events.go:450 +0x1528
cogentcore.org/core/core.(*Events).handleEvent(0x14012210108, {0x106d957e8, 0x14015155dc0})
	/Users/oreilly/go/src/cogentcore.org/core/core/events.go:166 +0x58
cogentcore.org/core/core.(*Stage).popupHandleEvent(0x14014c42960, {0x106d957e8, 0x14015155dc0})
	/Users/oreilly/go/src/cogentcore.org/core/core/popupstage.go:176 +0x8c
cogentcore.org/core/core.(*stages).popupHandleEvent(0x14000119bc0, {0x106d957e8, 0x14015155dc0})
	/Users/oreilly/go/src/cogentcore.org/core/core/popupstage.go:218 +0xe4
cogentcore.org/core/core.(*Stage).mainHandleEvent(0x14000250960, {0x106d957e8, 0x14015155dc0})
	/Users/oreilly/go/src/cogentcore.org/core/core/mainstage.go:359 +0x40
cogentcore.org/core/core.(*stages).mainHandleEvent(0x140003b61d0, {0x106d957e8, 0x14015155dc0})
	/Users/oreilly/go/src/cogentcore.org/core/core/mainstage.go:375 +0x78
cogentcore.org/core/core.(*renderWindow).handleEvent(0x140003b61a0, {0x106d957e8, 0x14015155dc0})
	/Users/oreilly/go/src/cogentcore.org/core/core/renderwindow.go:444 +0x1c8
cogentcore.org/core/core.(*renderWindow).eventLoop(0x140003b61a0)
	/Users/oreilly/go/src/cogentcore.org/core/core/renderwindow.go:407 +0x90
created by cogentcore.org/core/core.(*renderWindow).goStartEventLoop in goroutine 1
	/Users/oreilly/go/src/cogentcore.org/core/core/renderwindow.go:378 +0x6c
```

### Platform

macOS

**Comment by rcoreilly** [comment]
Note this will be fixed when the canvas branch is merged, per 4fef123
