### ISSUE TITLE
Dynamically adding items to the Tree in Maker causes a crash

### ISSUE THREAD

**Issue by sj14** [cogentcore/core#1069]
### Describe the bug

Add a loop inside the Maker func which adds new items to a tree crashes the program.

### How to reproduce

Add a loop inside the Maker func which adds new items to a tree.

### Example code

```go
package main

import (
	"cogentcore.org/core/core"
	"cogentcore.org/core/tree"
)

func main() {
	b := core.NewBody()

	tb := core.NewToolbar(b)
	tb.Maker(func(p *tree.Plan) {
		for _, s := range []string{"1", "2"} {
			tree.Add(p, func(w *core.Button) {
				w.SetText(s)
			})
		}
	})

	b.RunMainWindow()
}
```

### Relevant output

```shell
➜  test-gui git:(main) ✗ go run main.go
2024/07/28 15:36:25 panic: plan.Update: duplicate name: test-gui-main-go-14
2024/07/28 15:36:25 
2024/07/28 15:36:25 ----- START OF STACK TRACE: -----
2024/07/28 15:36:25 goroutine 1 [running, locked to thread]:
runtime/debug.Stack()
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/debug/stack.go:24 +0x64
cogentcore.org/core/system.HandleRecoverBase({0x1017b6160, 0x14000405810})
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/system/recover.go:50 +0x38
cogentcore.org/core/core.handleRecover({0x1017b6160, 0x14000405810})
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/core/recover.go:33 +0x48
cogentcore.org/core/core.(*Stage).run.func1()
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/core/stage.go:277 +0x34
panic({0x1017b6160?, 0x14000405810?})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/panic.go:770 +0x124
cogentcore.org/core/base/plan.Update[...](0x140003fe038, 0x3, 0x140000399a8, 0x14000039998, 0x14000039978, 0x1018e94c8)
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/base/plan/update.go:50 +0x864
cogentcore.org/core/tree.(*Plan).Update(0x140003b98f0, {0x1018f6c10, 0x140003fe008})
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/tree/plan.go:235 +0x100
cogentcore.org/core/tree.(*NodeBase).UpdateFromMake(0x140003fe008)
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/tree/plan.go:112 +0x8c
cogentcore.org/core/core.(*WidgetBase).UpdateWidget.(*NodeBase).RunUpdaters.func1({0x1400029a428, 0x101311120?, 0x101870180?})
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/tree/plan.go:121 +0x34
cogentcore.org/core/base/tiered.(*Tiered[...]).Do(0x10130bf40, 0x1018e93e0?)
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/base/tiered/tiered.go:30 +0x5c
cogentcore.org/core/tree.(*NodeBase).RunUpdaters(...)
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/tree/plan.go:119
cogentcore.org/core/core.(*WidgetBase).UpdateWidget(0x140003fe008)
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/core/update.go:25 +0x50
cogentcore.org/core/core.(*WidgetBase).UpdateTree.func1({0x101e5ff50?, 0x1018c4c20?}, 0x14000039c20?)
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/core/update.go:33 +0x20
cogentcore.org/core/core.(*WidgetBase).UpdateTree.(*WidgetBase).WidgetWalkDown.func2({0x1018f6850, 0x140003fe008})
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/core/widget.go:449 +0xa8
cogentcore.org/core/tree.(*NodeBase).WalkDown(0x1400030c888, 0x140003bb750)
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/tree/nodebase.go:500 +0xf0
cogentcore.org/core/core.(*WidgetBase).WidgetWalkDown(...)
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/core/widget.go:447
cogentcore.org/core/core.(*WidgetBase).UpdateTree(0x1400030c888)
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/core/update.go:32 +0x5c
cogentcore.org/core/core.(*Scene).updateScene(0x1400030c888?)
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/core/render.go:237 +0x50
cogentcore.org/core/core.(*Stage).configMainStage(0x140003a2960)
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/core/mainstage.go:163 +0x9c
cogentcore.org/core/core.(*Stage).runWindow(0x140003a2960)
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/core/mainstage.go:176 +0x11c
cogentcore.org/core/core.(*Stage).run(0x140003a2960?)
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/core/stage.go:280 +0x8c
cogentcore.org/core/core.(*Stage).Run(0x0?)
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/core/stage.go:259 +0x8c
cogentcore.org/core/core.(*Body).RunWindow(0x8?)
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/core/mainstage.go:69 +0x34
cogentcore.org/core/core.(*Body).RunMainWindow(0x0?)
        /Users/simon/go/pkg/mod/cogentcore.org/core@v0.3.0/core/mainstage.go:59 +0x134
main.main()
        /Users/simon/Desktop/test-gui/main.go:20 +0x114

2024/07/28 15:36:25 ----- END OF STACK TRACE -----
```

### Platform

macOS

**Comment by theclapp** [comment]
The error is "plan.Update: duplicate name: test-gui-main-go-14".

`tree.Add` says "The name of the node is automatically generated based on the file and line number of the calling function."

Using `tree.AddAt` and giving a unique name for each item (e.g. `s` in this example) fixes the panic.

```go
for _, s := range []string{"1", "2"} {
	tree.AddAt(p, s, func(w *core.Button) {
		w.SetText(s)
	})
}
```

Edit: I'm too new to CogentCore to know if this is the *right* solution, but it's *a* solution.

**Comment by sj14** [comment]
Thank you, that's a valid solution.

**Comment by kkoreilly** [comment]
Yes, that is the right solution! We do something similar in the documentation page for [plans](https://www.cogentcore.org/core/basics/plans). Thank you for answering, @theclapp!
