### ISSUE TITLE
Vulkan: Loader not found

### ISSUE THREAD

**Issue by j0hnsmith** [cogentcore/core#1106]
### Describe the bug

I'm trying to run the cogent hello world example on an arm64 mac. It compiles but doesn't run, I get the output below.

I've installed https://github.com/KhronosGroup/MoltenVK.

Any ideas what I'm missing?

### How to reproduce

Run the cogent hello world example on an arm64 mac.

### Example code

```go
package main

import (
	"cogentcore.org/core/core"
)

func main() {
	b := core.NewBody()
	core.NewButton(b).SetText("Hello, World!")
	b.RunMainWindow()
}
```

### Relevant output

```shell
go-gl/glfw: internal error: an uncaught error has occurred: APIUnavailable: Vulkan: Loader not found
go-gl/glfw: Please report this in the Go package issue tracker.
go-gl/glfw: internal error: an uncaught error has occurred: APIUnavailable: Vulkan: Loader not found
go-gl/glfw: Please report this in the Go package issue tracker.
go-gl/glfw: internal error: an invalid error was not accepted by the caller: APIUnavailable: Vulkan: Loader not found
go-gl/glfw: Please report this in the Go package issue tracker.
panic: APIUnavailable: Vulkan: Loader not found

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0x0, 0x0, 0x1?})
        {redacted}/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240307211618-a69d953ea142/error.go:181 +0x214
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
        {redacted}/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240307211618-a69d953ea142/error.go:188
github.com/go-gl/glfw/v3.3/glfw.WindowHint(0x10546bc88?, 0x104dba4a0?)
        {redacted}/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240307211618-a69d953ea142/window.go:274 +0x38
cogentcore.org/core/system/driver/desktop.(*App).InitVk(0x105f3f4c0)
        {redacted}/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/desktop/app.go:85 +0xd0
cogentcore.org/core/system/driver/desktop.Init()
        {redacted}/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/desktop/app.go:30 +0x28
cogentcore.org/core/system/driver.init.0()
        {redacted}/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/driver_desktop.go:30 +0xcc
```

### Platform

macOS

**Comment by kkoreilly** [comment]
Did you run `core setup` as documented in the [install instructions](https://www.cogentcore.org/core/setup/install)?

**Comment by j0hnsmith** [comment]
I hadn't, didn't realise any setup was required. I've run it now and it works as expected, thanks.
