### ISSUE TITLE
Crash when resizing window?

### ISSUE THREAD

**Issue by duggavo** [cogentcore/core#1247]
### Describe the bug

No matter what code I have, even the official examples crash when I resize the window.

Using Ubuntu 24 with X11:
```sh
user@host: echo $XDG_SESSION_TYPE
x11
```

Crash log:
```
thread '<unnamed>' panicked at src/lib.rs:3974:36:
invalid texture
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
SIGABRT: abort
PC=0x78b64d49eb1c m=11 sigcode=18446744073709551610
signal arrived during cgo execution
```
(and then there is a VERY long Go stacktrace... is it relevant?  I've pasted it here: https://paste.debian.net/plainh/3768a9a4 )

EDIT: i clearly remember everything was working fine a few months ago, maybe before 3.0? I'm currently running v0.3.4 

EDIT2: the Go version is `go1.23.2 linux/amd64`

### How to reproduce

Install Ubuntu 24 (it's using integrated intel cpu i think)

Run any cogent core example

Resize the window

### Platform

Linux

**Comment by kkoreilly** [comment]
Thank you for reporting this. Can you try these commands for me?

```sh
go run cogentcore.org/core/gpu/cmd/webgpuinfo@main
go run cogentcore.org/core/gpu/examples/drawtri@main
go run cogentcore.org/core/examples/basic@main
go run cogentcore.org/core/examples/basic@v0.3.0
go run cogentcore.org/core/examples/basic@v0.2.0
```

Can you paste in the output from the first command and then tell me in which of the other commands resizing works? Thank you!

**Comment by duggavo** [comment]
webgpuinfo output: https://paste.debian.net/hidden/703a61c4/

`go run cogentcore.org/core/gpu/examples/drawtri@main`:
```
thread '<unnamed>' panicked at src/lib.rs:3974:36:
invalid texture
```

basic@main: same error

basic@v0.3.0: works fine

basic@v0.2.0: works fine

**Comment by duggavo** [comment]
I've tested more v0.3.X versions.
v0.3.1 seems to be working fine too, v0.3.2 and later crash.

**Comment by duggavo** [comment]
Crash occurs when resizing the window vertically, horizontally or diagonally, both when shrinking and when increasing the window size. In case that might help, it doesn't always crash 100% of the times the mouse is moved, only after a little time.

Maximizing or de-maximizing the window doesn't trigger the crash. Only dragging with the mouse.

**Comment by kkoreilly** [comment]
Thank you for all of the information. `v0.3.2` is when we switched from Vulkan to WebGPU (#1112). Can you try `go run github.com/cogentcore/webgpu/examples/triangle@main` so we can determine whether this is a problem with the underlying WebGPU package? Thank you!

**Comment by duggavo** [comment]
@kkoreilly github.com/cogentcore/webgpu/examples/triangle@main works fine, no crash when resizing the window.

EDIT: however, it keeps printing warns like this:
```
[wgpu] [Warn] Suboptimal present of frame 1
[wgpu] [Warn] Suboptimal present of frame 1
[wgpu] [Warn] Suboptimal present of frame 1
[wgpu] [Warn] Suboptimal present of frame 1
[wgpu] [Warn] Suboptimal present of frame 1
[wgpu] [Warn] Suboptimal present of frame 2
[wgpu] [Warn] Suboptimal present of frame 1
[wgpu] [Warn] Suboptimal present of frame 1
[wgpu] [Warn] Suboptimal present of frame 1
[wgpu] [Warn] Suboptimal present of frame 1
[wgpu] [Warn] Suboptimal present of frame 2
[wgpu] [Warn] Suboptimal present of frame 0
[wgpu] [Warn] Suboptimal present of frame 1
```
when resizing the window.
It might be related?

**Comment by kkoreilly** [comment]
Thank you for all of the information. We will test this on our test Linux device and look into what we can do to fix this.

**Comment by rcoreilly** [comment]
I was able to replicate this on my linux laptop, with a discrete NVIDIA GPU. My first resize "grab and drag" usually works fine, but if I wait a beat and then resize again, it tends to crash (but not 100% reliably).

In any case, I believe the relevant wgpu issue is here: https://github.com/gfx-rs/wgpu/issues/3586 and there is a PR here: https://github.com/gfx-rs/wgpu/pull/6253 -- it seems to require a few updates before it can be applied, but otherwise has undergone review.

The issue is that wgpu (rust) is panicing before returning an error, so we don't even get to see the error and bail on the current render attempt, and try again next time, which is what the logic currently implements. It is somewhat unclear whether there is any actual possibility of recovery from the underlying cause of the problem, but we could try to reconfigure things again at least.. we can't do anything if we don't get the error, however.

**Comment by rcoreilly** [comment]
ps. the underlying bug that causes this appears to be specific to NVIDIA. I tried several different driver versions using the ubuntu-driver tool as described here: https://ubuntu.com/server/docs/nvidia-drivers-installation.  For my old-ish laptop with a Quadro T2000 chip, the driver that was originally installed worked by far the best (it was 535 something). 470 and any version of 550 all were significantly worse, causing the crash almost immediately. So if you have a version other than 535, you might try changing to that. This is the command to check:

cat /proc/driver/nvidia/version

The -open versions were notably slower overall and seemed unreliable - even 535-open crashed right away.

Overall, this seems like a really problematic issue for wgpu on linux, given the prevalence of NVIDIA GPUs. It might even be worth selecting the slower integrated device until this is resolved. e.g., try this:

export GPU_DEVICE_SELECT=0

and see how that goes? I could not get it to crash with this setting.  We probably actually want to change the default selection process on linux to favor the integrated device instead of the discrete one, if the discrete is nvidia.

**Comment by rcoreilly** [comment]
Ok the logic to avoid NVIDIA discrete GPU is now in place, in the #1341 PR, for both linux AND windows!

I just got the exact same crash on windows on the same laptop, so it apparently is a deep issue with nvidia drivers / hardware :(

**Comment by kkoreilly** [comment]
Just to be clear, #1341 implements a temporary fix that should prevent this problem from happening, but we will leave this issue open until https://github.com/gfx-rs/wgpu/pull/6253 is merged, as that fixes the true underlying issue. #1341 should be merged within a couple of days, and it will also implement #1329 in addition to preventing this issue from happening while resizing. Please let us know if you have any questions.

**Comment by kkoreilly** [comment]
As of #1341, this issue should not happen due to a temporary fix we implemented; please let us know if it still crashes when resizing for you. We also implemented #1329 in that PR. https://github.com/gfx-rs/wgpu/pull/6253 was merged and we made some other improvements to resizing logic in #1341, so we should have a permanent fix soon. We will leave this issue open until we implement the permanent fix.

**Comment by duggavo** [comment]
Hello.
Running with the latest commit version:
```
go run cogentcore.org/core/gpu/examples/drawtri@affbc2499b653f3d9f589d8cf8a62705584c4af5
```
still crashes:
```
wgpu] [Warn] Detected skylake derivative running on mesa i915. Clears to srgb textures will use manual shader clears.
format: Size: (1024,768)  Format:   MultiSample: 1  Layers: 1
thread '<unnamed>' panicked at src/lib.rs:3974:36:
invalid texture
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
SIGABRT: abort
PC=0x7b9e39a9eb1c m=0 sigcode=18446744073709551610
signal arrived during cgo execution
goroutine 1 gp=0xc0000061c0 m=0 mp=0xefb480 [syscall, locked to thread]:
runtime.cgocall(0x58d1f0, 0xc000157bc8)
	/usr/local/go/src/runtime/cgocall.go:167 +0x4b fp=0xc000157ba0 sp=0xc000157b68 pc=0x4a1c4b
github.com/cogentcore/webgpu/wgpu._Cfunc_wgpuTextureGetMipLevelCount(0x0)
	_cgo_gotypes.go:3259 +0x47 fp=0xc000157bc8 sp=0xc000157ba0 pc=0x51e7c7
cogentcore.org/core/gpu.(*Surface).GetCurrentTexture.(*Texture).GetMipLevelCount.func1(0x0?)
	/home/user/go/pkg/mod/github.com/cogentcore/webgpu@v0.0.0-20241209022019-c49c394fb750/wgpu/texture.go:102 +0x3f fp=0xc000157c08 sp=0xc000157bc8 pc=0x5858df
github.com/cogentcore/webgpu/wgpu.(*Texture).GetMipLevelCount(...)
	/home/user/go/pkg/mod/github.com/cogentcore/webgpu@v0.0.0-20241209022019-c49c394fb750/wgpu/texture.go:102
cogentcore.org/core/gpu.(*Surface).GetCurrentTexture(0xc000098008)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.6/gpu/surface.go:117 +0x7a fp=0xc000157c80 sp=0xc000157c08 pc=0x58571a
cogentcore.org/core/gpu.(*GraphicsSystem).beginRenderPass(0xc0000960a0)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.6/gpu/gsystem.go:215 +0x32 fp=0xc000157cd0 sp=0xc000157c80 pc=0x5837f2
cogentcore.org/core/gpu.(*GraphicsSystem).BeginRenderPass(0xc0000960a0)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.6/gpu/gsystem.go:234 +0x18 fp=0xc000157d20 sp=0xc000157cd0 pc=0x5838f8
main.main.func3()
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.6/gpu/examples/drawtri/drawtri.go:65 +0x46 fp=0xc000157db8 sp=0xc000157d20 pc=0x58b246
main.main()
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.6/gpu/examples/drawtri/drawtri.go:100 +0x51c fp=0xc000157f50 sp=0xc000157db8 pc=0x58b19c

(... more cgo stacktrace here, please let me know if you need it)
```

**Comment by rcoreilly** [comment]
@duggavo can you run with this env var set:

export GPU_DEVICE_SELECT=0

so we are 100% sure it is using the integrated intel chip.

And also can you try running examples/demo too?  that now goes through a different pathway for resizing, and it might work better?

In my testing I was unable to get the integrated GPU to crash at all despite at least a couple of minutes of persistent resizing..

And in the latest code, even with the NVIDIA GPU, it took quite a while to get the crash from it, and it now went through a different pathway.

How long does it take you to get the crash? right away?

**Comment by prospero78** [comment]
Im not have Intel GPU (AMD+Nvidia). After run im look crash simple app from docs.

**Comment by kkoreilly** [comment]
@prospero78 Thank you for replying. Is it the same crash stack trace as before? Can you please provide the output from this command? Thanks!

```sh
go run cogentcore.org/core/gpu/cmd/webgpuinfo@main
```

**Comment by prospero78** [comment]
```bash
user@user-B650M-DS3H:~$ go run cogentcore.org/core/gpu/cmd/webgpuinfo@main
go: downloading cogentcore.org/core v0.3.8-0.20241224074244-8b26e9d6c068
[wgpu] [Warn] No config found!
[wgpu] [Warn] EGL says it can present to the window but not natively

#####################################################################
WebGPU Adapter number: 0   Type: discrete-gpu   Backend: vulkan
{
        "VendorId": 4318,
        "VendorName": "0x10de",
        "Architecture": "",
        "DeviceId": 9602,
        "Name": "0x2582",
        "DriverDescription": "NVIDIA GeForce RTX 3050",
        "AdapterType": 0,
        "BackendType": 6
}

{
        "Limits": {
                "MaxTextureDimension1D": 32768,
                "MaxTextureDimension2D": 32768,
                "MaxTextureDimension3D": 16384,
                "MaxTextureArrayLayers": 2048,
                "MaxBindGroups": 8,
                "MaxBindingsPerBindGroup": 1000,
                "MaxDynamicUniformBuffersPerPipelineLayout": 15,
                "MaxDynamicStorageBuffersPerPipelineLayout": 16,
                "MaxSampledTexturesPerShaderStage": 1048576,
                "MaxSamplersPerShaderStage": 1048576,
                "MaxStorageBuffersPerShaderStage": 1048576,
                "MaxStorageTexturesPerShaderStage": 1048576,
                "MaxUniformBuffersPerShaderStage": 1048576,
                "MaxUniformBufferBindingSize": 65536,
                "MaxStorageBufferBindingSize": 2147483648,
                "MinUniformBufferOffsetAlignment": 64,
                "MinStorageBufferOffsetAlignment": 32,
                "MaxVertexBuffers": 16,
                "MaxBufferSize": 18446744073709551615,
                "MaxVertexAttributes": 32,
                "MaxVertexBufferArrayStride": 2048,
                "MaxInterStageShaderComponents": 128,
                "MaxInterStageShaderVariables": 0,
                "MaxColorAttachments": 0,
                "MaxColorAttachmentBytesPerSample": 0,
                "MaxComputeWorkgroupStorageSize": 49152,
                "MaxComputeInvocationsPerWorkgroup": 1024,
                "MaxComputeWorkgroupSizeX": 1024,
                "MaxComputeWorkgroupSizeY": 1024,
                "MaxComputeWorkgroupSizeZ": 64,
                "MaxComputeWorkgroupsPerDimension": 65535,
                "MaxPushConstantSize": 0
        }
}


#####################################################################
WebGPU Adapter number: 1   Type: discrete-gpu   Backend: vulkan
{
        "VendorId": 4318,
        "VendorName": "0x10de",
        "Architecture": "",
        "DeviceId": 9602,
        "Name": "0x2582",
        "DriverDescription": "NVIDIA GeForce RTX 3050",
        "AdapterType": 0,
        "BackendType": 6
}

{
        "Limits": {
                "MaxTextureDimension1D": 32768,
                "MaxTextureDimension2D": 32768,
                "MaxTextureDimension3D": 16384,
                "MaxTextureArrayLayers": 2048,
                "MaxBindGroups": 8,
                "MaxBindingsPerBindGroup": 1000,
                "MaxDynamicUniformBuffersPerPipelineLayout": 15,
                "MaxDynamicStorageBuffersPerPipelineLayout": 16,
                "MaxSampledTexturesPerShaderStage": 1048576,
                "MaxSamplersPerShaderStage": 1048576,
                "MaxStorageBuffersPerShaderStage": 1048576,
                "MaxStorageTexturesPerShaderStage": 1048576,
                "MaxUniformBuffersPerShaderStage": 1048576,
                "MaxUniformBufferBindingSize": 65536,
                "MaxStorageBufferBindingSize": 2147483648,
                "MinUniformBufferOffsetAlignment": 64,
                "MinStorageBufferOffsetAlignment": 32,
                "MaxVertexBuffers": 16,
                "MaxBufferSize": 18446744073709551615,
                "MaxVertexAttributes": 32,
                "MaxVertexBufferArrayStride": 2048,
                "MaxInterStageShaderComponents": 128,
                "MaxInterStageShaderVariables": 0,
                "MaxColorAttachments": 0,
                "MaxColorAttachmentBytesPerSample": 0,
                "MaxComputeWorkgroupStorageSize": 49152,
                "MaxComputeInvocationsPerWorkgroup": 1024,
                "MaxComputeWorkgroupSizeX": 1024,
                "MaxComputeWorkgroupSizeY": 1024,
                "MaxComputeWorkgroupSizeZ": 64,
                "MaxComputeWorkgroupsPerDimension": 65535,
                "MaxPushConstantSize": 0
        }
}


#####################################################################
WebGPU Adapter number: 2   Type: integrated-gpu   Backend: vulkan
{
        "VendorId": 4098,
        "VendorName": "0x1002",
        "Architecture": "",
        "DeviceId": 5710,
        "Name": "0x164e",
        "DriverDescription": "AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO)",
        "AdapterType": 1,
        "BackendType": 6
}

{
        "Limits": {
                "MaxTextureDimension1D": 16384,
                "MaxTextureDimension2D": 16384,
                "MaxTextureDimension3D": 2048,
                "MaxTextureArrayLayers": 2048,
                "MaxBindGroups": 8,
                "MaxBindingsPerBindGroup": 1000,
                "MaxDynamicUniformBuffersPerPipelineLayout": 16,
                "MaxDynamicStorageBuffersPerPipelineLayout": 8,
                "MaxSampledTexturesPerShaderStage": 8388606,
                "MaxSamplersPerShaderStage": 8388606,
                "MaxStorageBuffersPerShaderStage": 8388606,
                "MaxStorageTexturesPerShaderStage": 8388606,
                "MaxUniformBuffersPerShaderStage": 8388606,
                "MaxUniformBufferBindingSize": 2147483648,
                "MaxStorageBufferBindingSize": 2147483648,
                "MinUniformBufferOffsetAlignment": 32,
                "MinStorageBufferOffsetAlignment": 32,
                "MaxVertexBuffers": 16,
                "MaxBufferSize": 2147483647,
                "MaxVertexAttributes": 32,
                "MaxVertexBufferArrayStride": 2048,
                "MaxInterStageShaderComponents": 128,
                "MaxInterStageShaderVariables": 0,
                "MaxColorAttachments": 0,
                "MaxColorAttachmentBytesPerSample": 0,
                "MaxComputeWorkgroupStorageSize": 65536,
                "MaxComputeInvocationsPerWorkgroup": 1024,
                "MaxComputeWorkgroupSizeX": 1024,
                "MaxComputeWorkgroupSizeY": 1024,
                "MaxComputeWorkgroupSizeZ": 1024,
                "MaxComputeWorkgroupsPerDimension": 65535,
                "MaxPushConstantSize": 813003886
        }
}


#####################################################################
WebGPU Adapter number: 3   Type: cpu   Backend: vulkan
{
        "VendorId": 65541,
        "VendorName": "0x10005",
        "Architecture": "",
        "DeviceId": 0,
        "Name": "0x0",
        "DriverDescription": "llvmpipe (LLVM 17.0.6, 256 bits)",
        "AdapterType": 2,
        "BackendType": 6
}

{
        "Limits": {
                "MaxTextureDimension1D": 16384,
                "MaxTextureDimension2D": 16384,
                "MaxTextureDimension3D": 4096,
                "MaxTextureArrayLayers": 2048,
                "MaxBindGroups": 8,
                "MaxBindingsPerBindGroup": 1000,
                "MaxDynamicUniformBuffersPerPipelineLayout": 1000000,
                "MaxDynamicStorageBuffersPerPipelineLayout": 1000000,
                "MaxSampledTexturesPerShaderStage": 1000000,
                "MaxSamplersPerShaderStage": 1000000,
                "MaxStorageBuffersPerShaderStage": 1000000,
                "MaxStorageTexturesPerShaderStage": 1000000,
                "MaxUniformBuffersPerShaderStage": 1000000,
                "MaxUniformBufferBindingSize": 65536,
                "MaxStorageBufferBindingSize": 134217728,
                "MinUniformBufferOffsetAlignment": 32,
                "MinStorageBufferOffsetAlignment": 32,
                "MaxVertexBuffers": 16,
                "MaxBufferSize": 2147483647,
                "MaxVertexAttributes": 32,
                "MaxVertexBufferArrayStride": 2048,
                "MaxInterStageShaderComponents": 128,
                "MaxInterStageShaderVariables": 0,
                "MaxColorAttachments": 0,
                "MaxColorAttachmentBytesPerSample": 0,
                "MaxComputeWorkgroupStorageSize": 32768,
                "MaxComputeInvocationsPerWorkgroup": 1024,
                "MaxComputeWorkgroupSizeX": 1024,
                "MaxComputeWorkgroupSizeY": 1024,
                "MaxComputeWorkgroupSizeZ": 1024,
                "MaxComputeWorkgroupsPerDimension": 65535,
                "MaxPushConstantSize": 813003886
        }
}


#####################################################################
WebGPU Adapter number: 4   Type: unknown   Backend: open-gl
{
        "VendorId": 4318,
        "VendorName": "0x10de",
        "Architecture": "",
        "DeviceId": 0,
        "Name": "0x0",
        "DriverDescription": "NVIDIA GeForce RTX 3050/PCIe/SSE2",
        "AdapterType": 3,
        "BackendType": 7
}

{
        "Limits": {
                "MaxTextureDimension1D": 32768,
                "MaxTextureDimension2D": 32768,
                "MaxTextureDimension3D": 16384,
                "MaxTextureArrayLayers": 2048,
                "MaxBindGroups": 8,
                "MaxBindingsPerBindGroup": 65535,
                "MaxDynamicUniformBuffersPerPipelineLayout": 14,
                "MaxDynamicStorageBuffersPerPipelineLayout": 16,
                "MaxSampledTexturesPerShaderStage": 16,
                "MaxSamplersPerShaderStage": 16,
                "MaxStorageBuffersPerShaderStage": 16,
                "MaxStorageTexturesPerShaderStage": 8,
                "MaxUniformBuffersPerShaderStage": 14,
                "MaxUniformBufferBindingSize": 65536,
                "MaxStorageBufferBindingSize": 2147483647,
                "MinUniformBufferOffsetAlignment": 256,
                "MinStorageBufferOffsetAlignment": 32,
                "MaxVertexBuffers": 16,
                "MaxBufferSize": 2147483647,
                "MaxVertexAttributes": 16,
                "MaxVertexBufferArrayStride": 2048,
                "MaxInterStageShaderComponents": 124,
                "MaxInterStageShaderVariables": 0,
                "MaxColorAttachments": 0,
                "MaxColorAttachmentBytesPerSample": 0,
                "MaxComputeWorkgroupStorageSize": 49152,
                "MaxComputeInvocationsPerWorkgroup": 1024,
                "MaxComputeWorkgroupSizeX": 1024,
                "MaxComputeWorkgroupSizeY": 1024,
                "MaxComputeWorkgroupSizeZ": 64,
  
```

**Comment by kkoreilly** [comment]
@prospero78 *Edit: see the next comment below first*

Thank you for that helpful information. Can you please try this command:

```sh
export GPU_DEVICE_SELECT=2
```

And then run your code again and see if it works. Please also try this:

```sh
export GPU_DEVICE_SELECT=3
```

And then run your code again and let us know if it works. Hopefully at least one of those should work.

**Comment by kkoreilly** [comment]
@prospero78 @duggavo Actually, it turns out we didn't activate the right selection logic in #1341, so that is why it wasn't working. We just fixed that in #1403, so this should work without any environment variables now (this is the latest commit on the main branch):

```sh
go run cogentcore.org/core/examples/demo@0a17ddf
```

Please try that and let me know if it works. You don't need to try the environment variables if the command above works. Thank you for your patience.
