### ISSUE TITLE
Crash when clicking on plus button in empty inline map view

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#680]
Stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference

----- START OF STACK TRACE: -----
goroutine 163 [running]:
runtime/debug.Stack()
	C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x5e
goki.dev/goosi.HandleRecoverBase({0x7ff7f01307c0, 0x7ff7f0010410})
	C:/msys64/home/Kai/goki/goosi/recover.go:50 +0x4b
goki.dev/goosi.glob..func1({0x7ff7f01307c0, 0x7ff7f0010410})
	C:/msys64/home/Kai/goki/goosi/recover.go:33 +0x1d
goki.dev/gi/v2/gi.(*RenderWin).EventLoop.func1()
	C:/msys64/home/Kai/goki/gi/gi/renderwin.go:558 +0x24
panic({0x7ff7f01307c0?, 0x7ff7f0010410?})
	C:/Program Files/Go/src/runtime/panic.go:914 +0x21f
goki.dev/gi/v2/gi.(*WidgetBase).RunStylers(...)
	C:/msys64/home/Kai/goki/gi/gi/style.go:183
goki.dev/gi/v2/gi.(*WidgetBase).ApplyStyleWidget(0xc0000a0000)
	C:/msys64/home/Kai/goki/gi/gi/style.go:108 +0x80
goki.dev/gi/v2/gi.(*WidgetBase).ApplyStyle(0xc0000a0000)
	C:/msys64/home/Kai/goki/gi/gi/style.go:218 +0x6e
goki.dev/gi/v2/gi.(*WidgetBase).Update.func1({0x7ff7f1aa3cb8, 0xc0000a0000}, 0x7ff7f1a6e3e8?)
	C:/msys64/home/Kai/goki/gi/gi/render.go:330 +0x34
goki.dev/gi/v2/gi.(*WidgetBase).Update.(*WidgetBase).WidgetWalkPre.func2({0x7ff7f1a90148?, 0xc0000a0000?})
	C:/msys64/home/Kai/goki/gi/gi/widget.go:515 +0xab
goki.dev/ki/v2.(*Node).WalkPre(0xc0000a0000, 0xc004533160)
	C:/msys64/home/Kai/goki/ki/node.go:983 +0x1ad
goki.dev/gi/v2/gi.(*WidgetBase).WidgetWalkPre(...)
	C:/msys64/home/Kai/goki/gi/gi/widget.go:510
goki.dev/gi/v2/gi.(*WidgetBase).Update(0xc0000a0000)
	C:/msys64/home/Kai/goki/gi/gi/render.go:328 +0x1da
goki.dev/gi/v2/giv.(*StructView).ConfigStructGrid.func4({0x7ff7f1a82d98, 0xc0045649a0})
	C:/msys64/home/Kai/goki/gi/giv/structview.go:327 +0xd9
goki.dev/goosi/events.(*Listeners).Call(0xc002f6f408, {0x7ff7f1a82d98, 0xc0045649a0})
	C:/msys64/home/Kai/goki/goosi/events/listeners.go:58 +0xa2
goki.dev/gi/v2/giv.(*ValueBase).HandleEvent(0xc000082c00?, {0x7ff7f1a82d98?, 0xc0045649a0?})
	C:/msys64/home/Kai/goki/gi/giv/value.go:616 +0x12a
goki.dev/gi/v2/giv.(*ValueBase).Send(0xc001f097f0?, 0x23, {0x0?, 0x7ff7f01a0440?, 0x1?})
	C:/msys64/home/Kai/goki/gi/giv/value.go:605 +0x85
goki.dev/gi/v2/giv.(*ValueBase).SendChange(...)
	C:/msys64/home/Kai/goki/gi/giv/value.go:588
goki.dev/gi/v2/giv.(*SliceInlineValue).ConfigWidget.func1({0xc004db9200?, 0x0?})
	C:/msys64/home/Kai/goki/gi/giv/values.go:614 +0x25
goki.dev/gi/v2/gi.(*WidgetBase).OnLast.func1({0x7ff7f1a82d98, 0xc0045648c0})
	C:/msys64/home/Kai/goki/gi/gi/events.go:48 +0x9f
goki.dev/goosi/events.(*Listeners).Call(0xc004db9900, {0x7ff7f1a82d98, 0xc0045648c0})
	C:/msys64/home/Kai/goki/goosi/events/listeners.go:58 +0xa2
goki.dev/gi/v2/gi.(*WidgetBase).HandleEvent(0xc004db9200, {0x7ff7f1a82d98, 0xc0045648c0})
	C:/msys64/home/Kai/goki/gi/gi/events.go:198 +0x1f5
goki.dev/gi/v2/gi.(*WidgetBase).Send(0xc004db9200, 0x23, {0x0, 0x0, 0x0?})
	C:/msys64/home/Kai/goki/gi/gi/events.go:134 +0x18c
goki.dev/gi/v2/gi.(*WidgetBase).SendChange(...)
	C:/msys64/home/Kai/goki/gi/gi/events.go:141
goki.dev/gi/v2/giv.(*SliceViewInline).SetChanged(...)
	C:/msys64/home/Kai/goki/gi/giv/sliceviewinline.go:205
goki.dev/gi/v2/giv.(*SliceViewInline).SliceNewAt(0xc004db9200, 0x80?)
	C:/msys64/home/Kai/goki/gi/giv/sliceviewinline.go:222 +0xd7
goki.dev/gi/v2/giv.(*SliceViewInline).OnInit.(*SliceViewInline).SetStyles.func2.2({0xc001b57800?, 0x7ff7f1a7aa28?})
	C:/msys64/home/Kai/goki/gi/giv/sliceviewinline.go:67 +0x1e
goki.dev/gi/v2/gi.(*WidgetBase).OnClick.(*WidgetBase).On.func1({0x7ff7f1a82d98, 0xc0045647e0})
	C:/msys64/home/Kai/goki/gi/gi/events.go:35 +0x6f
goki.dev/goosi/events.(*Listeners).Call(0xc001b57f00, {0x7ff7f1a82d98, 0xc0045647e0})
	C:/msys64/home/Kai/goki/goosi/events/listeners.go:58 +0xa2
goki.dev/gi/v2/gi.(*WidgetBase).HandleEvent(0xc001b57800, {0x7ff7f1a82d98, 0xc0045647e0})
	C:/msys64/home/Kai/goki/gi/gi/events.go:198 +0x1f5
goki.dev/gi/v2/gi.(*WidgetBase).Send(0xc001b57800, 0x5, {0xc00419c6d0, 0x1, 0x1?})
	C:/msys64/home/Kai/goki/gi/gi/events.go:134 +0x18c
goki.dev/gi/v2/gi.(*EventMgr).HandlePosEvent(0xc0001b2108, {0x7ff7f1a83258, 0xc00909e380})
	C:/msys64/home/Kai/goki/gi/gi/eventmgr.go:385 +0x849
goki.dev/gi/v2/gi.(*EventMgr).HandleEvent(0xc00412b8f0?, {0x7ff7f1a83258, 0xc00909e380})
	C:/msys64/home/Kai/goki/gi/gi/eventmgr.go:178 +0x5a
goki.dev/gi/v2/gi.(*Stage).MainHandleEvent(0xc004197d40, {0x7ff7f1a83258?, 0xc00909e380})
	C:/msys64/home/Kai/goki/gi/gi/mainstage.go:303 +0x15d
goki.dev/gi/v2/gi.(*StageMgr).MainHandleEvent(0xc004274f18, {0x7ff7f1a83258, 0xc00909e380})
	C:/msys64/home/Kai/goki/gi/gi/mainstage.go:311 +0x6e
goki.dev/gi/v2/gi.(*RenderWin).HandleEvent(0xc004274ee0, {0x7ff7f1a83258, 0xc00909e380})
	C:/msys64/home/Kai/goki/gi/gi/renderwin.go:604 +0x166
goki.dev/gi/v2/gi.(*RenderWin).EventLoop(0xc004274ee0)
	C:/msys64/home/Kai/goki/gi/gi/renderwin.go:570 +0x5e
created by goki.dev/gi/v2/gi.(*RenderWin).GoStartEventLoop in goroutine 31
	C:/msys64/home/Kai/goki/gi/gi/renderwin.go:526 +0xa5

----- END OF STACK TRACE -----
```

**Comment by kkoreilly** [comment]
Closing in favor of the more general #679.
