### ISSUE TITLE
crash in SetCursor -- probably when window is closing or has closed

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#763]
```
oreilly@bshadow:~/Library/goki/crash-logs/gide/ > more crash_2024-01-08_11-06-34 
panic: runtime error: invalid memory address or nil pointer dereference

----- START OF STACK TRACE: -----
goroutine 1575510 [running]:
runtime/debug.Stack()
        /opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/debug/stack.go:24 +0x64
goki.dev/goosi.HandleRecoverBase({0x103309d60, 0x103f5fa90})
        /Users/oreilly/go/src/goki.dev/goosi/recover.go:50 +0x38
goki.dev/goosi.glob..func1({0x103309d60, 0x103f5fa90})
        /Users/oreilly/go/src/goki.dev/goosi/recover.go:33 +0x24
goki.dev/gi/v2/gi.(*RenderWin).EventLoop.func1()
        /Users/oreilly/go/src/goki.dev/gi/v2/gi/renderwin.go:558 +0x34
panic({0x103309d60?, 0x103f5fa90?})
        /opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/panic.go:914 +0x218
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetCursor.func2(0x14064807af8?, 0x101392bc8?)
        /Users/oreilly/go/src/github.com/go-gl/glfw/v3.3/glfw/input.go:532 +0x20
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetCursor(0x103301380?, 0x1400619d710?)
        /Users/oreilly/go/src/github.com/go-gl/glfw/v3.3/glfw/input.go:532 +0x20
goki.dev/goosi/driver/desktop.(*Cursor).Set(0x103f6d100, {0x1034a50a8, 0x103fc4940})
        /Users/oreilly/go/src/goki.dev/goosi/driver/desktop/cursor.go:45 +0x1d4
goki.dev/gi/v2/gi.(*EventMgr).SetCursor(0x141361dd160?, 0x34b21e8?)
        /Users/oreilly/go/src/goki.dev/gi/v2/gi/eventmgr.go:760 +0xcc
goki.dev/gi/v2/gi.(*EventMgr).HandlePosEvent(0x14101936508, {0x1034b21e8, 0x140cd020c40})
        /Users/oreilly/go/src/goki.dev/gi/v2/gi/eventmgr.go:430 +0xe10
goki.dev/gi/v2/gi.(*EventMgr).HandleEvent(0x14136023490?, {0x1034b21e8, 0x140cd020c40})
        /Users/oreilly/go/src/goki.dev/gi/v2/gi/eventmgr.go:178 +0x58
goki.dev/gi/v2/gi.(*Stage).MainHandleEvent(0x141361d8240, {0x1034b21e8?, 0x140cd020c40})
        /Users/oreilly/go/src/goki.dev/gi/v2/gi/mainstage.go:303 +0x144
goki.dev/gi/v2/gi.(*StageMgr).MainHandleEvent(0x1402048a038, {0x1034b21e8, 0x140cd020c40})
        /Users/oreilly/go/src/goki.dev/gi/v2/gi/mainstage.go:311 +0x78
goki.dev/gi/v2/gi.(*RenderWin).HandleEvent(0x1402048a000, {0x1034b21e8, 0x140cd020c40})
        /Users/oreilly/go/src/goki.dev/gi/v2/gi/renderwin.go:604 +0x128
goki.dev/gi/v2/gi.(*RenderWin).EventLoop(0x1402048a000)
        /Users/oreilly/go/src/goki.dev/gi/v2/gi/renderwin.go:570 +0x50
created by goki.dev/gi/v2/gi.(*RenderWin).GoStartEventLoop in goroutine 1228817
        /Users/oreilly/go/src/goki.dev/gi/v2/gi/renderwin.go:526 +0xa4

----- END OF STACK TRACE -----
```

**Comment by kkoreilly** [comment]
Does this still happen? If so, is there any way to trigger it so I can debug it? I have never had this happen since v2.

**Comment by rcoreilly** [comment]
very rare -- probably best to just see if there is a convenient nil check to guard?

**Comment by kkoreilly** [comment]
Just got this again.
