### ISSUE TITLE
The text editor is stuttering when loading large files

### ISSUE THREAD

**Issue by ddkwork** [cogentcore/core#889]
### Describe the bug

see title

### How to reproduce

[xxx.zip](https://github.com/cogentcore/core/files/14310703/xxx.zip)

Unzip the zip file is a json file, drag and drop the json file to the window, it takes several seconds to load it on the text editor, and drag the scrollbar after loading it

### Example code

```go
package main

import (
	"cogentcore.org/core/goosi/driver/desktop"
	"embed"
	"github.com/ddkwork/golibrary/stream"
	"github.com/go-gl/glfw/v3.3/glfw"

	"cogentcore.org/core/gi"
	"cogentcore.org/core/styles"
	"cogentcore.org/core/texteditor"
)

//go:embed texteditor.go
var samplefile embed.FS

func main() {
	b := gi.NewBody("Cogent Core Text Editor Demo")

	sp := gi.NewSplits(b)
	sp.SetSplits(.5, .5)
	// these are all inherited so we can put them at the top "editor panel" level
	sp.Style(func(s *styles.Style) {
		s.Text.WhiteSpace = styles.WhiteSpacePreWrap
		s.Text.TabSize = 4
		s.Font.Family = string(gi.AppearanceSettings.MonoFont)
	})

	te1 := texteditor.NewEditor(sp)
	te1.Style(func(s *styles.Style) {
		s.Min.X.Ch(20)
		s.Min.Y.Ch(10)
	})
	te2 := texteditor.NewEditor(sp)
	te2.Style(func(s *styles.Style) {
		s.Min.X.Ch(20)
		s.Min.Y.Ch(10)
	})

	tb := texteditor.NewBuf()
	te1.SetBuf(tb)
	te2.SetBuf(tb)

	tb.Hi.Lang = "Go"
	tb.OpenFS(samplefile, "texteditor.go")
	NewWindowRunAndWait(b, func(names []string) {
		s := stream.NewReadFile(names[0])
		tb.SetText(s.Bytes())
		te1.SetBuf(tb)
		te2.SetBuf(tb)
	})
	
}

func NewWindowRunAndWait(b *gi.Body, DropCallback func(names []string)) {
	w := b.NewWindow().Run()
	if w == nil || w.MainMgr == nil || w.MainMgr.RenderWin == nil {
		return
	}
	win := w.MainMgr.RenderWin.GoosiWin
	ww, ok := win.(*desktop.Window)
	if ok {
		ww.Glw.SetDropCallback(func(w *glfw.Window, names []string) {
			if DropCallback != nil {
				DropCallback(names)
			}
		})
	}
	w.Wait()
}

```

### Relevant output

```shell
see title
```

### Platform

Windows

**Comment by ddkwork** [comment]
![screenshots](https://github.com/cogentcore/core/assets/19886504/52c5386c-a863-43db-8c2b-080cbece6357)

**Comment by ddkwork** [comment]
The GIF situation recorded this time is a little better, and the scroll bar cannot be operated several times before, and sometimes the main window is stuck

**Comment by ddkwork** [comment]
The GIF situation recorded this time is a little better, and the scroll bar cannot be operated several times before, and sometimes the main window is stuck

**Comment by ddkwork** [comment]
Hit the close button in the top right corner and it will happen every time
```go
GOROOT=C:\Users\Admin\go\pkg\mod\golang.org\toolchain@v0.0.1-go1.22.0.windows-amd64 #gosetup
GOPATH=C:\Users\Admin\go #gosetup
C:\Users\Admin\go\pkg\mod\golang.org\toolchain@v0.0.1-go1.22.0.windows-amd64\bin\go.exe build -o C:\Users\Admin\AppData\Local\JetBrains\GoLand2023.3\tmp\GoLand\___1go_build_github_com_ddkwork_workspace_filetree_texteditor.exe github.com/ddkwork/workspace/filetree/texteditor #gosetup
C:\Users\Admin\AppData\Local\JetBrains\GoLand2023.3\tmp\GoLand\___1go_build_github_com_ddkwork_workspace_filetree_texteditor.exe
   Trace [2024-02-16 04:14:21]    --------- title --------- | ------------------ info ------------------ //runtime.doInit1 proc.go:7176
2024/02/16 04:14:23 INFO panic: interface conversion: interface is nil, not gi.Widget
2024/02/16 04:14:23 INFO 
2024/02/16 04:14:23 INFO ----- START OF STACK TRACE: -----
2024/02/16 04:14:23 INFO goroutine 1 [running, locked to thread]:
runtime/debug.Stack()
        C:/Users/Admin/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.windows-amd64/src/runtime/debug/stack.go:24 +0x5e
cogentcore.org/core/goosi.HandleRecoverBase({0x7ff7c6765d00, 0xc000211890})
        D:/workspace/workspace/core/goosi/recover.go:49 +0x4b
cogentcore.org/core/gi.HandleRecover({0x7ff7c6765d00, 0xc000211890})
        D:/workspace/workspace/core/gi/recover.go:32 +0x4b
cogentcore.org/core/gi.(*Stage).RunImpl.func1()
        D:/workspace/workspace/core/gi/stage.go:300 +0x24
panic({0x7ff7c6765d00?, 0xc000211890?})
        C:/Users/Admin/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.windows-amd64/src/runtime/panic.go:770 +0x132
cogentcore.org/core/gi.(*WidgetBase).OnFinal(0xc000343508, 0x1b, 0xc001412c30)
        D:/workspace/workspace/core/gi/events.go:66 +0x1b1
cogentcore.org/core/gi.(*Layout).HandleKeys(...)
        D:/workspace/workspace/core/gi/layout.go:308
cogentcore.org/core/gi.(*Layout).HandleEvents(0xc000343508)
        D:/workspace/workspace/core/gi/layout.go:292 +0x74
cogentcore.org/core/gi.(*Frame).OnInit(0xc000343508)
        D:/workspace/workspace/core/gi/frame.go:20 +0x1e
cogentcore.org/core/gi.(*Body).OnInit(0xc000343508)
        D:/workspace/workspace/core/gi/body.go:50 +0x1e
cogentcore.org/core/ki.InitNode({0x7ff7c7de5cd8, 0xc000343508})
        D:/workspace/workspace/core/ki/admin.go:32 +0xa2
cogentcore.org/core/ki.(*Node).AddChild(0xc000292588, {0x7ff7c7de5cd8, 0xc000343508})
        D:/workspace/workspace/core/ki/node.go:439 +0x4b
cogentcore.org/core/gi.(*Scene).ConfigSceneBars(0xc000292588)
        D:/workspace/workspace/core/gi/bars.go:83 +0x2b5
cogentcore.org/core/gi.(*Stage).ConfigMainStage(0xc00140e008)
        D:/workspace/workspace/core/gi/mainstage.go:104 +0x68
cogentcore.org/core/gi.(*Stage).RunWindow(0xc00140e008)
        D:/workspace/workspace/core/gi/mainstage.go:118 +0x130
cogentcore.org/core/gi.(*Stage).RunImpl(0x7ff7c7c62b30?)
        D:/workspace/workspace/core/gi/stage.go:303 +0xac
cogentcore.org/core/gi.(*Stage).Run(0xc000000000?)
        D:/workspace/workspace/core/gi/stage.go:282 +0x7a
cogentcore.org/core/gi.(*Body).RunMainWindow(0xc000369c08?)
        D:/workspace/workspace/core/gi/mainstage.go:38 +0x26
main.main()
        D:/workspace/workspace/filetree/texteditor/texteditor.go:52 +0x3ef

2024/02/16 04:14:23 INFO ----- END OF STACK TRACE -----
2024/02/16 04:14:23 INFO SAVED CRASH LOG TO C:\Users\Admin\AppData\Roaming\Cogent Core Text Editor Demo\crash-logs\crash_2024-02-16_04-14-23
2024/02/16 04:14:23 INFO panic: runtime error: invalid memory address or nil pointer dereference
2024/02/16 04:14:23 INFO
2024/02/16 04:14:23 INFO ----- START OF STACK TRACE: -----
2024/02/16 04:14:23 INFO goroutine 1 [running, locked to thread]:
runtime/debug.Stack()
        C:/Users/Admin/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.windows-amd64/src/runtime/debug/stack.go:24 +0x5e
cogentcore.org/core/goosi.HandleRecoverBase({0x7ff7c6760d60, 0x7ff7c66038c0})
        D:/workspace/workspace/core/goosi/recover.go:49 +0x4b
cogentcore.org/core/gi.HandleRecover({0x7ff7c6760d60, 0x7ff7c66038c0})
        D:/workspace/workspace/core/gi/recover.go:32 +0x4b
cogentcore.org/core/gi.(*Stage).RunImpl.func1()
        D:/workspace/workspace/core/gi/stage.go:300 +0x24
panic({0x7ff7c6760d60?, 0x7ff7c66038c0?})
        C:/Users/Admin/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.windows-amd64/src/runtime/panic.go:770 +0x132
cogentcore.org/core/goosi/driver/desktop.(*Window).WinSize(0x0?)
        <autogenerated>:1 +0x9
cogentcore.org/core/goosi.(*NewWindowOptions).Fixup(0xc001ac0000)
        D:/workspace/workspace/core/goosi/window.go:363 +0x20d
cogentcore.org/core/goosi/driver/desktop.(*App).NewWindow(0x7ff7c8771da0, 0x7ff7c8771a7c?)
        D:/workspace/workspace/core/goosi/driver/desktop/app.go:117 +0x146
cogentcore.org/core/gi.NewRenderWin({0xc00142a040, 0x3d}, {0xc00142a000, 0x31}, 0xc001ac0000)
        D:/workspace/workspace/core/gi/renderwin.go:172 +0xa6
cogentcore.org/core/gi.(*Stage).NewRenderWin(0xc00140e248)
        D:/workspace/workspace/core/gi/mainstage.go:280 +0x1fd
cogentcore.org/core/gi.(*Stage).RunWindow(0xc00140e248)
        D:/workspace/workspace/core/gi/mainstage.go:166 +0x672
cogentcore.org/core/gi.(*Stage).RunImpl(0x7ff7c67eea00?)
        D:/workspace/workspace/core/gi/stage.go:303 +0xac
cogentcore.org/core/gi.(*Stage).Run(0x0?)
        D:/workspace/workspace/core/gi/stage.go:282 +0x7a
cogentcore.org/core/gi.HandleRecover({0x7ff7c6765d00, 0xc000211890})
        D:/workspace/workspace/core/gi/recover.go:67 +0x21a
cogentcore.org/core/gi.(*Stage).RunImpl.func1()
        D:/workspace/workspace/core/gi/stage.go:300 +0x24
panic({0x7ff7c6765d00?, 0xc000211890?})
        C:/Users/Admin/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.windows-amd64/src/runtime/panic.go:770 +0x132
cogentcore.org/core/gi.(*WidgetBase).OnFinal(0xc000343508, 0x1b, 0xc001412c30)
        D:/workspace/workspace/core/gi/events.go:66 +0x1b1
cogentcore.org/core/gi.(*Layout).HandleKeys(...)
        D:/workspace/workspace/core/gi/layout.go:308
cogentcore.org/core/gi.(*Layout).HandleEvents(0xc000343508)
        D:/workspace/workspace/core/gi/layout.go:292 +0x74
cogentcore.org/core/gi.(*Frame).OnInit(0xc000343508)
        D:/workspace/workspace/core/gi/frame.go:20 +0x1e
cogentcore.org/core/gi.(*Body).OnInit(0xc000343508)
        D:/workspace/workspace/core/gi/body.go:50 +0x1e
cogentcore.org/core/ki.InitNode({0x7ff7c7de5cd8, 0xc000343508})
        D:/workspace/workspace/core/ki/admin.go:32 +0xa2
cogentcore.org/core/ki.(*Node).AddChild(0xc000292588, {0x7ff7c7de5cd8, 0xc000343508})
        D:/workspace/workspace/core/ki/node.go:439 +0x4b
cogentcore.org/core/gi.(*Scene).ConfigSceneBars(0xc000292588)
        D:/workspace/workspace/core/gi/bars.go:83 +0x2b5
cogentcore.org/core/gi.(*Stage).ConfigMainStage(0xc00140e008)
        D:/workspace/workspace/core/gi/mainstage.go:104 +0x68
cogentcore.org/core/gi.(*Stage).RunWindow(0xc00140e008)
        D:/workspace/workspace/core/gi/mainstage.go:118 +0x130
cogentcore.org/core/gi.(*Stage).RunImpl(0x7ff7c7c62b30?)
        D:/workspace/workspace/core/gi/stage.go:303 +0xac
cogentcore.org/core/gi.(*Stage).Run(0xc000000000?)
        D:/workspace/workspace/core/gi/stage.go:282 +0x7a
cogentcore.org/core/gi.(*Body).RunMainWindow(0xc000369c08?)
        D:/workspace/workspace/core/gi/mainstage.go:38 +0x26
main.main()
        D:/workspace/workspace/filetree/texteditor/texteditor.go:52 +0x3ef

2024/02/16 04:14:23 INFO ----- END OF STACK TRACE -----
2024/02/16 04:14:23 INFO SAVED CRASH LOG TO C:\Users\Admin\AppData\Roaming\Cogent Core Text Editor Demo\crash-logs\crash_2024-02-16_04-14-23



```

**Comment by kkoreilly** [comment]
I will look into this.

**Comment by ddkwork** [comment]
> I will look into this.

```go
func BenchmarkEditor_SetBuf(b *testing.B) {
	body := gi.NewBody("Cogent Core Text Editor Demo")
	te1 := texteditor.NewEditor(body)
	tb := texteditor.NewBuf()

	path := "C:\\Users\\Admin\\Desktop\\xxx.js"
	s := stream.NewReadFile(path)

	for i := 0; i < b.N; i++ {
		tb.SetText(s.Bytes())
		te1.SetBuf(tb)
		//BenchmarkEditor_SetBuf-8              48          22019879 ns/op
		//BenchmarkEditor_SetBuf-8              50          21977296 ns/op
		//BenchmarkEditor_SetBuf-8              49          23003624 ns/op
		//BenchmarkEditor_SetBuf-8              50          22451284 ns/op
		//BenchmarkEditor_SetBuf-8              51          22763486 ns/op
		//BenchmarkEditor_SetBuf-8              50          23213716 ns/op
		//BenchmarkEditor_SetBuf-8              52          21766925 ns/op
		//BenchmarkEditor_SetBuf-8              39          32967277 ns/op
	}
}
```

**Comment by ddkwork** [comment]
Hello, I have conducted several stress tests and the code can be set up within approximately 1.6 seconds. However, after running the main function and dragging and dropping the file to set it up, it takes 6-17 seconds. Which functions should I further stress test?

**Comment by kkoreilly** [comment]
The cause of the delay is likely the syntax highlighting, which happens in `SetFilename`, not `SetBuf`.

**Comment by ddkwork** [comment]
> The cause of the delay is likely the syntax highlighting, which happens in `SetFilename`, not `SetBuf`.

Okay, I'm going to read the code carefully and comment out the two aspects of the code to test again, but if that's the case, I think I should stress test the syntax coloring, because it could be caused by one function related to the syntax coloring but not all of it. I think the code editor needs 100% test coverage, write unit tests for all relevant functions, and stress test for all relevant functions, so that we can run the test again after making any subsequent changes, before we are ready to commit the code, as long as the performance of the loading code is optimal, we can rely on various tests to keep it stable.

**Comment by kkoreilly** [comment]
I agree, and I will write text editor tests in the context of #541.

**Comment by ddkwork** [comment]
> The cause of the delay is likely the syntax highlighting, which happens in `SetFilename`, not `SetBuf`.

After debugging, I found that the following three functions are causing stuttering, any good suggestions?
```go
	tb.BytesToLines()
	tb.InitialMarkup()
	tb.ReMarkup()
```

**Comment by ddkwork** [comment]
For BytesToLines, I remember that there was a way to get high performance through regular expressions, and I was going to add stress tests to the three functions I mentioned, but I'm not sure if I can properly simulate the structure and data, so it would be better if you wrote a stress test

**Comment by kkoreilly** [comment]
I will look into this soon.

**Comment by ddkwork** [comment]
> I will look into this soon.

```go
func BenchmarkReaderReadLine(b *testing.B) {
	s := stream.NewReadFile("D:\\clone\\HyperDbg\\hyperdbg\\demo\\xxx.js")
	for i := 0; i < b.N; i++ {
		s.ToLines() //about 1.5s
		//BenchmarkReaderReadLine-8         513292              2254 ns/op
		//BenchmarkReaderReadLine-8         348691              3156 ns/op
		//BenchmarkReaderReadLine-8         390274              3068 ns/op
		//BenchmarkReaderReadLine-8         471577              2296 ns/op
		//BenchmarkReaderReadLine-8         325484              3568 ns/op
		//BenchmarkReaderReadLine-8         370736              2860 ns/op
		//BenchmarkReaderReadLine-8         390140              3054 ns/op
	}
}

func BenchmarkByStringsSplitAfter(b *testing.B) {
	s := stream.NewReadFile("D:\\clone\\HyperDbg\\hyperdbg\\demo\\xxx.js")
	for i := 0; i < b.N; i++ {
		strings.SplitAfter(s.String(), "\n") //about
		//BenchmarkByStringsSplitAfter-8               355           3617550 ns/op
		//BenchmarkByStringsSplitAfter-8               332           4132401 ns/op
		//BenchmarkByStringsSplitAfter-8               248           4461010 ns/op
		//BenchmarkByStringsSplitAfter-8               370           3778242 ns/op
		//BenchmarkByStringsSplitAfter-8               247           4556421 ns/op
		//BenchmarkByStringsSplitAfter-8               303           4366858 ns/op
	}
}

func BenchmarkByBytessSplitAfter(b *testing.B) {
	s := stream.NewReadFile("D:\\clone\\HyperDbg\\hyperdbg\\demo\\xxx.js")
	for i := 0; i < b.N; i++ {
		bytes.SplitAfter(s.Bytes(), []byte("\n")) //about
		//BenchmarkByBytessSplitAfter-8                613           1812570 ns/op
		//BenchmarkByBytessSplitAfter-8                450           2775832 ns/op
		//BenchmarkByBytessSplitAfter-8                468           2581962 ns/op
		//BenchmarkByBytessSplitAfter-8                460           3021967 ns/op
		//BenchmarkByBytessSplitAfter-8                430           3010534 ns/op
	}
}

func BenchmarkByRegexp(b *testing.B) { //todo
	s := stream.NewReadFile("D:\\clone\\HyperDbg\\hyperdbg\\demo\\xxx.js")
	re := regexp.MustCompile(`\n`)
	for i := 0; i < b.N; i++ {
		re.Split(s.String(), -1) //about
		//BenchmarkByRegexp-8           48          22047369 ns/op
		//BenchmarkByRegexp-8           36          32086147 ns/op
		//BenchmarkByRegexp-8           38          32875274 ns/op
		//BenchmarkByRegexp-8           62          18963963 ns/op
		//BenchmarkByRegexp-8           34          32556691 ns/op
	}
}

// Split a string on "\n" while preserving them. The output can be used
// as input for UnifiedDiff and ContextDiff structures.
func SplitLines(s string) []string {
	//bytes.Split()
	//bytes.SplitAfter()
	lines := strings.SplitAfter(s, "\n")
	lines[len(lines)-1] += "\n"
	return lines
}
```

**Comment by ddkwork** [comment]
I have an idea to avoid the problem of stuckness when opening a 1.4MB file: we judge the size of the file after reading it, and if it exceeds 0.3MB, it will be cut into a slice and stored in a map, and then we will convert the first buffer in the slice into lines, and then fill it in the relevant fields, and have done things such as coloring, and do the same thing when we are about to return and open a separate thread for each slice, and pop the slice out after each thread's function is executed. In this way, no matter how large the file is, it shouldn't be opened on the stuck.,Wait,1.4MB file tried several ways to write it in 1.5 seconds at the fastest time to convert to lines.,The experience is not good.。 I don't know how EverEdit can open files in seconds, but is there a good idea for coloring at the moment? Is it possible to shade in threads in segments?

**Comment by ddkwork** [comment]
Maybe my bad English translation is inaccurate, but it's actually just this logic: split the file, in the thread, in sections, and the large file only processes the first segment of the split result for the first time. What do you think?

**Comment by kkoreilly** [comment]
I will consider this idea.

**Comment by ddkwork** [comment]
> I will consider this idea.

```go
package main

import (
	"bufio"
	"fmt"
	"io"
	"log"
	"os"
	"time"
)

func main() {
	var (
		m11 = `C:\Users\Admin\go\pkg\mod\fyne.io\fyne\v2@v2.4.4\theme\bundled-emoji.go`
		m62 = `D:\Desktop\packets.json`
	)
	ReadFileSubTimeWithCallBack("m11 os.file.read 1024 byte every time(block)", m11, func(s string) { readBlock(m11) })
	ReadFileSubTimeWithCallBack("m11 os.file.read byte file size once", m11, func(s string) { readAllBuff(m11) })
	ReadFileSubTimeWithCallBack("m11 os.ReadFile", m11, func(s string) { readAll(m11) })
	ReadFileSubTimeWithCallBack("m11 bufio ReadLine", m11, func(s string) { readEachLineReader(m11) })
	ReadFileSubTimeWithCallBack("m11 bufio Scanner ------------> seems fast", m11, func(s string) { readEachLineScanner(m11) })

	ReadFileSubTimeWithCallBack("m62 os.file.read 1024 byte every time(block)", m62, func(s string) { readBlock(m62) })
	ReadFileSubTimeWithCallBack("m62 os.file.read byte file size once", m62, func(s string) { readAllBuff(m62) })
	ReadFileSubTimeWithCallBack("m62 os.ReadFile", m62, func(s string) { readAll(m62) })
	ReadFileSubTimeWithCallBack("m62 bufio ReadLine", m62, func(s string) { readEachLineReader(m62) })
	ReadFileSubTimeWithCallBack("m62 bufio Scanner ------------> seems fast", m62, func(s string) { readEachLineScanner(m62) })

}

func readBlock(filePath string) {
	FileHandle, err := os.Open(filePath)
	if err != nil {
		log.Println(err)
		return
	}
	defer FileHandle.Close()
	buffer := make([]byte, 1024)
	for {
		n, err := FileHandle.Read(buffer)
		if err != nil && err != io.EOF {
			log.Println(err)
		}
		if n == 0 {
			break
		}
	}
}

func readEachLineReader(filePath string) {
	FileHandle, err := os.Open(filePath)
	if err != nil {
		log.Println(err)
		return
	}
	defer FileHandle.Close()
	lines := make([]byte, 0)
	lineReader := bufio.NewReader(FileHandle)
	for {
		// func (b *Reader) ReadLine() (line []byte, isPrefix bool, err error)
		// func (b *Reader) ReadBytes(delim byte) (line []byte, err error)
		// func (b *Reader) ReadString(delim byte) (line string, err error)
		line, _, err := lineReader.ReadLine()
		if err == io.EOF {
			break
		}
		lines = append(lines, line...)
	}
}

func readEachLineScanner(filePath string) {
	FileHandle, err := os.Open(filePath)
	if err != nil {
		log.Println(err)
		return
	}
	defer FileHandle.Close()
	lineScanner := bufio.NewScanner(FileHandle)
	lines := make([]byte, 0)
	for lineScanner.Scan() {
		// func (s *Scanner) Bytes() []byte
		// func (s *Scanner) Text() string
		lines = append(lines, lineScanner.Bytes()...)
	}
}

func readAll(filePath string) {
	os.ReadFile(filePath)
}

func readAllBuff(filePath string) {
	FileHandle, err := os.Open(filePath)
	if err != nil {
		log.Println(err)
		return
	}
	defer FileHandle.Close()
	fileInfo, err := FileHandle.Stat()
	if err != nil {
		log.Println(err)
		return
	}
	buffer := make([]byte, fileInfo.Size())
	_, err = FileHandle.Read(buffer)
	if err != nil {
		log.Println(err)
	}
}

func ReadFileSubTimeWithCallBack(title, path string, callBack func(string)) {
	now := time.Now()
	callBack(path)
	sub := time.Now().Sub(now)
	fmt.Printf(" %-48s spend | %s \n", title, sub)
}

GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\Admin\go #gosetup
"C:\Program Files\Go\bin\go.exe" build -o C:\Users\Admin\AppData\Local\JetBrains\GoLand2023.3\tmp\GoLand\___go_build_awesomeProject1.exe awesomeProject1 #gosetup
C:\Users\Admin\AppData\Local\JetBrains\GoLand2023.3\tmp\GoLand\___go_build_awesomeProject1.exe
 m11 os.file.read 1024 byte every time(block)     spend | 35.8397ms
 m11 os.file.read byte file size once             spend | 10.7065ms
 m11 os.ReadFile                                  spend | 10.4844ms
 m11 bufio ReadLine                               spend | 33.3904ms
 m11 bufio Scanner ------------> seems fast       spend | 1.5066ms
 m62 os.file.read 1024 byte every time(block)     spend | 185.0628ms
 m62 os.file.read byte file size once             spend | 54.0325ms
 m62 os.ReadFile                                  spend | 50.3137ms
 m62 bufio ReadLine                               spend | 180.5446ms
 m62 bufio Scanner ------------> seems fast       spend | 109.9535ms 

```

**Comment by ddkwork** [comment]
Maybe could used github.com/allegro/bigcache

**Comment by kkoreilly** [comment]
That is an interesting idea that I will consider, but it should not be necessary for the performance improvements for opening files that I will work on soon.

**Comment by ddkwork** [comment]
Ok

**Comment by ddkwork** [comment]
I've reimplemented syntax highlighting with unison and have come to the conclusion that:large file loading performance needs to be improved by improving chroma to support streaming reads and also changing to streaming rendering within any gui libs, which is going to take some time to look into, do you know of any other libs that don't use regular expressions to parse tokens other than chroma? Regular expressions don't seem to support streaming mode operations!
![Screenshot_20240427_152130_com.realvnc.viewer.android.jpg](https://github.com/cogentcore/core/assets/19886504/2a4b3636-dcb8-49d3-837f-76d091a4a570)

**Comment by kkoreilly** [comment]
Again, as I said above, I am going to improve the performance of the text editor as soon as I have the time. I guarantee you we will have good large file loading performance.
