### ISSUE TITLE
I run the example video in freebsd it have error

### ISSUE THREAD

**Issue by runsys** [cogentcore/core#998]
### Describe the bug

video example in freebsd invalid memory address error.

### How to reproduce

just run it.

### Relevant output

```shell
/da/go/src/cogentcore.org/core/examples/video/video  [/da/go/src/cogentcore.org/core/examples/video]
2024/07/01 23:36:51 ERROR girl/paint.FontLib: programmer error: no font paths; need to add some
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1640511]

goroutine 1 [running, locked to thread]:
github.com/ebitengine/oto.NewContext(0x898039ea0?)
	/da/go/src/github.com/ebitengine/oto/context.go:93 +0xb1
github.com/faiface/beep/speaker.Init(0x8983d0008?, 0x113a)
	/da/go/src/github.com/faiface/beep/speaker/speaker.go:40 +0x1c6
cogentcore.org/core/video.(*Video).Open(0x8983e6008, {0x3a9b7c, 0x8})
	/da/go/src/cogentcore.org/core/video/video.go:92 +0x30
main.main()
	/da/go/src/cogentcore.org/core/examples/video/video.go:29 +0x4ef
Command exited with code 2.
```

### Platform

macOS

**Comment by kkoreilly** [comment]
I will look into this issue and improving BSD support soon (relevant to #572).
